version: '{build}'
os: Visual Studio 2017
configuration: Debug
environment:	
  COVERALLS_REPO_TOKEN:	OIOtHgYfWwvDZb4a9MuFC398RJyW7qq8N
skip_branch_with_pr: true
build_script:
- ps: ./Build.ps1
test_script:
- ps: ./Coverage.ps1
artifacts:
  - path: '*.nupkg'
  - path: 'src\**\*.nupkg'
    name: NuGet Packages
  - path: 'src\**\*.snupkg'
    name: NuGet Symbol Packages
deploy:
  provider: NuGet
  api_key:
    secure: QeC34B7ohkvqbwCOKmavQWhitZNYLX/EFdgK8CfL5jEujWw2L85qrzuME8CQRBEb
  on:
    APPVEYOR_REPO_TAG: true
